spring.application.name=estacionamiento
server.port=8080
#server.port=8090
spring.datasource.url=jdbc:postgresql://localhost:5432/estacionamiento

#spring.datasource.url=jdbc:postgresql://db-postgresql-nyc3-28547-do-user-11334331-0.b.db.ondigitalocean.com:25060/estacionamiento?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=admin

#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto= update
spring.jpa.hibernate.show-sql=true


app.ratePerMinute=30
app.capacity=28
app.jwt.secret=Z3VhcmRhciBiaWVuIGxhcyBwbGFjYXMgc2VjdXJhcyE=
app.jwt.expMinutes=600

# Dirección base del servicio
#parking.server.url=http://186.64.113.173
parking.server.url=http://localhost:5173